apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harvester-vm-dhcp-controller.fullname" . }}
  labels:
    {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harvester-vm-dhcp-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "harvester-vm-dhcp-controller.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - --name
          - {{ include "harvester-vm-dhcp-controller.fullname" . }}
          - --namespace
          - {{ .Release.Namespace }}
          # --image # Rimosso: l'agent ora ha il suo deployment
          # - "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}" # Rimosso
          # --service-account-name # Rimosso
          # - {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-agent # Rimosso
          ports:
          - name: metrics
            protocol: TCP
            containerPort: {{ .Values.service.metricsPort }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harvester-vm-dhcp-controller.fullname" . }}-webhook
  labels:
    {{- include "harvester-vm-dhcp-webhook.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.webhook.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "harvester-vm-dhcp-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "harvester-vm-dhcp-webhook.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-webhook
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - --name
          - {{ include "harvester-vm-dhcp-controller.fullname" . }}-webhook
          - --namespace
          - {{ .Release.Namespace }}
          - --https-port
          - "{{ .Values.webhook.httpsPort }}"
          ports:
          - name: https
            protocol: TCP
            containerPort: {{ .Values.webhook.httpsPort }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
