apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
rules:
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "watch", "list", "update", "patch", "create" ]
- apiGroups: [ "network.harvesterhci.io" ]
  resources: [ "ippools", "ippools/status", "virtualmachinenetworkconfigs", "virtualmachinenetworkconfigs/status" ]
  verbs: [ "*" ]
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources: [ "network-attachment-definitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "watch", "list" ]
- apiGroups: [ "kubevirt.io" ]
  resources: [ "virtualmachines" ]
  verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-agent
rules:
- apiGroups: [ "network.harvesterhci.io" ]
  resources: [ "ippools", "ippools/status" ]
  verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
rules:
- apiGroups: [ "admissionregistration.k8s.io" ]
  resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
  verbs: [ "list", "update", "create" ]
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "customresourcedefinitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "apiregistration.k8s.io" ]
  resources: [ "apiservices" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "network.harvesterhci.io" ]
  resources: [ "ippools", "virtualmachinenetworkconfigs" ]
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources: [ "nodes" ]
  verbs: [ "watch", "list" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "watch", "list", "create", "update", "patch" ]
- apiGroups: [ "k8s.cni.cncf.io" ]
  resources: [ "network-attachment-definitions" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [ "kubevirt.io" ]
  resources: [ "virtualmachines" ]
  verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-agent
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-agent
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-webhook
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-deployment-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-agent-deployments
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }} # Controller's SA
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-deployment-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-lease-manager
  namespace: kube-system
rules:
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "watch", "list", "update", "create" ]
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "leases" ]
  verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-pod-manager
rules:
- apiGroups: [ "" ]
  resources: [ "pods" ]
  verbs: [ "get", "create", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-secret-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-leases
  namespace: kube-system
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-lease-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-manage-pods
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-pod-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-manage-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "harvester-vm-dhcp-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "harvester-vm-dhcp-controller.name" . }}-webhook-secret-manager
subjects:
- kind: ServiceAccount
  name: {{ include "harvester-vm-dhcp-controller.serviceAccountName" . }}-webhook
  namespace: {{ .Release.Namespace }}

